# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest 

    container:
      image: tojomcmo/ctrl-sandbox-env:amd64_latest
      volumes: 
        - ${{ github.workspace }}:/workspace

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: create and source venv
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
      
    - name: Install dependencies
      run: |  
        poetry install
        
    - name: Check flake8 version
      run: |
        poetry run flake8 --version        

    - name: Lint with flake8
      run: |
        poetry run flake8 . --max-line-length=88 --exclude .venv
      continue-on-error: true  
        
    - name: Test with pytest
      run: |
        poetry run pytest

